version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - laravel
    command: >
      sh -c "
      php artisan migrate --force &&
      php artisan db:seed --force &&
      /usr/bin/supervisord -c /etc/supervisor/supervisord.conf"

  web:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - laravel


volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
